### ISSUE TITLE
Create new release based off master

### ISSUE THREAD

**Issue by dcarbone** [Comcast/compare-ini-files#1]
Hey there,

Could you please create a new tag / release based off the latest version in master?  The version that is installed when using brew has issues in `parseConfLinesIsStanza` that have been resolved in the master branch.

Thanks!

**Comment by dmuth** [comment]
Hmm... I switched to `main` awhile ago, but I may need to fix what Homebrew does.  Let me look into this and get back to you.

**Comment by dmuth** [comment]
Oh yeah, looks like version 1.0 was way old!  I just created version 1.1 [here](https://github.com/Comcast/compare-ini-files/releases/tag/compare-ini-files-1.1) and then I updated [the Homebrew formula](https://github.com/Comcast/homebrew-opensource/blob/main/Formula/compare-ini-files.rb) so that should address the issue.

Please give it a shot and let me know if that fixes things for you (it did for me).

-- Doug

**Comment by dcarbone** [comment]
works great now!  thanks!
